language: node_js
node_js:
  - "7"
  - "6"
  - "4"
before_install:
  - npm i -g npm@latest
  - sudo sysctl fs.inotify.max_user_watches=524288
before_script"
  - npm install git://github.com/kulshekhar/ts-jest.git#long-dir-name
  - npm ls --depth=0
  
sudo: required
